version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven"
      - yum install -y maven
      - echo "Installing AWS SAM CLI"
      - pip install --upgrade aws-sam-cli
    finally:
      - echo "Installation completed on `date`"
      - sam --version
      - mvn -version
  pre_build:
    commands:
      - echo "Running tests"
      - mvn test

  build:
    commands:
      - echo "Building the JAR file"
      - mvn clean package
      - echo "Packaging the SAM application"
      - sam package --template-file UploadNotificationFunctionTemplate.yaml --output-template-file packaged.yaml --s3-bucket awscourseprojectsambucketcourse

  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - packaged.yaml
    - target/UploadsNotificationFunction-0.0.1-SNAPSHOT.jar

cache:
  paths:
    - '/root/.m2/**/*'