spring:
    datasource:
        url: jdbc:aws-wrapper:postgresql://awscourseprojectdb.cvqk8y2kugon.us-east-1.rds.amazonaws.com:5432/images3
        username: awscourse
        driver-class-name: software.amazon.jdbc.Driver
        hikari:
            data-source-properties:
                wrapperPlugins: iam,failover,efm2
                iamRegion: us-east-1
                iamExpiration: 840 # 14 min
            exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException
            max-lifetime: 84000 # 14 min
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

aws:
    s3:
        bucket:
            name: ${AWS_S3_BUCKET_NAME}
            region: ${AWS_S3_BUCKET_REGION}
