server:
    port: 8081
spring:
    datasource:
        url: ${RDS_CONNECTION_URL:jdbc:aws-wrapper:postgresql://images3.cvqk8y2kugon.us-east-1.rds.amazonaws.com:5432/images3}
        username: awscourse
        driver-class-name: software.amazon.jdbc.Driver
        hikari:
            data-source-properties:
                wrapperPlugins: iam,failover,efm2
                iamRegion: us-east-1
                iamExpiration: 840 # 14 min
            exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException
            max-lifetime: 84000 # 14 min
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    cloud:
        aws:
            sns:
                region: ${AWS_SNS_REGION:us-east-1}
            sqs:
                region: ${AWS_SQS_REGION:us-east-1}
            s3:
                bucket:
                    name: ${AWS_S3_BUCKET_NAME:images3rdsappawscourse}
                    region: ${AWS_S3_BUCKET_REGION:us-east-1}


io:
    reflectoring:
        aws:
            sns:
                topic-arn: ${AWS_SNS_TOPIC_ARN:arn:aws:sns:us-east-1:340752819584:awscourseproject-UploadsNotificationTopic}
            sqs:
                queue-url: ${AWS_SQS_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/340752819584/awscourseproject-UploadsNotificationQueue}

logging:
    file:
        name: /usr/log/mys3rdsapp.log
    level:
        root: INFO
        org.springframework: INFO

management:
    endpoints:
        web:
            exposure:
                include: health,info